// Copyright 2025 Carnegie Mellon University. All Rights Reserved.
// Released under a MIT (SEI)-style license. See LICENSE.md in the project root for license information.

#nullable enable

namespace Crucible.Common.EntityEvents.Abstractions;

/// <summary>
/// Marker interface for entity events generated by the <see cref="Interceptors.EntityEventInterceptor"/>.
/// Consuming applications can extend the event classes with additional interfaces
/// (e.g., MediatR's INotification) by creating partial class declarations in the same namespace.
/// </summary>
public interface IEntityEvent { }
