// Copyright 2026 Carnegie Mellon University. All Rights Reserved.
// Released under a MIT (SEI)-style license. See LICENSE.md in the project root for license information.

using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Crucible.Common.EntityEvents.Generators;

/// <summary>
/// Generates partial class declarations for EntityCreated, EntityUpdated, and EntityDeleted
/// that implement interfaces specified via the GenerateEntityEventInterfaces attribute.
/// </summary>
[Generator(LanguageNames.CSharp)]
public class EntityEventInterfaceGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Crucible.Common.EntityEvents.GenerateEntityEventInterfacesAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // ForAttributeWithMetadataName finds all classes with our attribute automatically
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetInterfaceTypes(ctx))
            .SelectMany(static (types, _) => types)
            .Collect();

        context.RegisterSourceOutput(provider, GenerateCode);
    }

    private static ImmutableArray<string> GetInterfaceTypes(GeneratorAttributeSyntaxContext context)
    {
        var types = ImmutableArray.CreateBuilder<string>();

        // The attribute has a params Type[] constructor, so we get an array of TypedConstants
        foreach (var arg in context.Attributes[0].ConstructorArguments)
        {
            if (arg.Kind == TypedConstantKind.Array)
            {
                foreach (var element in arg.Values)
                {
                    if (element.Value is INamedTypeSymbol namedType)
                    {
                        types.Add(namedType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                    }
                }
            }
            else if (arg.Value is INamedTypeSymbol namedType)
            {
                types.Add(namedType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            }
        }

        return types.ToImmutable();
    }

    private static void GenerateCode(SourceProductionContext context, ImmutableArray<string> interfaceTypes)
    {
        var uniqueTypes = interfaceTypes.Distinct().ToList();

        if (uniqueTypes.Count == 0) return;

        var interfaceList = string.Join(", ", uniqueTypes);
        var source = $$"""
            // <auto-generated/>
            #nullable enable

            namespace Crucible.Common.EntityEvents.Events
            {
                public partial class EntityCreated<TEntity> : {{interfaceList}} { }
                public partial class EntityUpdated<TEntity> : {{interfaceList}} { }
                public partial class EntityDeleted<TEntity> : {{interfaceList}} { }
            }
            """;

        context.AddSource("EntityEventInterfaces.g.cs", source);
    }
}
