// Copyright 2026 Carnegie Mellon University. All Rights Reserved.
// Released under a MIT (SEI)-style license. See LICENSE.md in the project root for license information.

using System.Collections.Immutable;
using Crucible.Common.EntityEvents.Generators;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Crucible.Common.Tests.EntityEvents;

public class EntityEventInterfaceGeneratorTests
{
    [Fact]
    public void Generator_WithSingleAttribute_GeneratesPartialClasses()
    {
        var source = """
            using System;

            namespace Crucible.Common.EntityEvents
            {
                [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
                public class GenerateEntityEventInterfacesAttribute : Attribute
                {
                    public Type[] InterfaceTypes { get; }
                    public GenerateEntityEventInterfacesAttribute(params Type[] interfaceTypes)
                    {
                        InterfaceTypes = interfaceTypes;
                    }
                }
            }

            public interface ITestNotification { }

            [Crucible.Common.EntityEvents.GenerateEntityEventInterfaces(typeof(ITestNotification))]
            public class TestDbContext { }
            """;

        var (generatedCode, diagnostics) = RunGenerator(source);

        // Report any compilation diagnostics for debugging
        Assert.Empty(diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error));

        Assert.NotNull(generatedCode);
        Assert.Contains("public partial class EntityCreated<TEntity> : global::ITestNotification", generatedCode);
        Assert.Contains("public partial class EntityUpdated<TEntity> : global::ITestNotification", generatedCode);
        Assert.Contains("public partial class EntityDeleted<TEntity> : global::ITestNotification", generatedCode);
    }

    [Fact]
    public void Generator_WithMultipleTypes_GeneratesMultipleInterfaces()
    {
        var source = """
            using System;

            namespace Crucible.Common.EntityEvents
            {
                [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
                public class GenerateEntityEventInterfacesAttribute : Attribute
                {
                    public Type[] InterfaceTypes { get; }
                    public GenerateEntityEventInterfacesAttribute(params Type[] interfaceTypes)
                    {
                        InterfaceTypes = interfaceTypes;
                    }
                }
            }

            public interface INotification1 { }
            public interface INotification2 { }

            [Crucible.Common.EntityEvents.GenerateEntityEventInterfaces(typeof(INotification1), typeof(INotification2))]
            public class TestDbContext { }
            """;

        var (generatedCode, diagnostics) = RunGenerator(source);

        Assert.Empty(diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error));
        Assert.NotNull(generatedCode);
        Assert.Contains("global::INotification1", generatedCode);
        Assert.Contains("global::INotification2", generatedCode);
    }

    [Fact]
    public void Generator_WithNoAttribute_GeneratesNoCode()
    {
        var source = """
            public class TestClass { }
            """;

        var (generatedCode, _) = RunGenerator(source);

        Assert.Null(generatedCode);
    }

    [Fact]
    public void Generator_WithNamespacedInterface_UsesFullyQualifiedName()
    {
        var source = """
            using System;

            namespace Crucible.Common.EntityEvents
            {
                [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
                public class GenerateEntityEventInterfacesAttribute : Attribute
                {
                    public Type[] InterfaceTypes { get; }
                    public GenerateEntityEventInterfacesAttribute(params Type[] interfaceTypes)
                    {
                        InterfaceTypes = interfaceTypes;
                    }
                }
            }

            namespace MyApp.Events
            {
                public interface IMyNotification { }
            }

            [Crucible.Common.EntityEvents.GenerateEntityEventInterfaces(typeof(MyApp.Events.IMyNotification))]
            public class TestDbContext { }
            """;

        var (generatedCode, diagnostics) = RunGenerator(source);

        Assert.Empty(diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error));
        Assert.NotNull(generatedCode);
        Assert.Contains("global::MyApp.Events.IMyNotification", generatedCode);
    }

    [Fact]
    public void Generator_OutputsAutoGeneratedComment()
    {
        var source = """
            using System;

            namespace Crucible.Common.EntityEvents
            {
                [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
                public class GenerateEntityEventInterfacesAttribute : Attribute
                {
                    public Type[] InterfaceTypes { get; }
                    public GenerateEntityEventInterfacesAttribute(params Type[] interfaceTypes)
                    {
                        InterfaceTypes = interfaceTypes;
                    }
                }
            }

            public interface ITest { }

            [Crucible.Common.EntityEvents.GenerateEntityEventInterfaces(typeof(ITest))]
            public class TestDbContext { }
            """;

        var (generatedCode, diagnostics) = RunGenerator(source);

        Assert.Empty(diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error));
        Assert.NotNull(generatedCode);
        Assert.Contains("// <auto-generated/>", generatedCode);
        Assert.Contains("#nullable enable", generatedCode);
        Assert.Contains("namespace Crucible.Common.EntityEvents.Events", generatedCode);
    }

    private static (string? GeneratedCode, ImmutableArray<Diagnostic> Diagnostics) RunGenerator(string source)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(source);

        var references = AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => !a.IsDynamic && !string.IsNullOrEmpty(a.Location))
            .Select(a => MetadataReference.CreateFromFile(a.Location))
            .Cast<MetadataReference>()
            .ToList();

        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            [syntaxTree],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new EntityEventInterfaceGenerator();

        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out var generatorDiagnostics);

        var results = driver.GetRunResult();
        var generatedSource = results.GeneratedTrees.FirstOrDefault();

        // Combine compilation and generator diagnostics
        var allDiagnostics = outputCompilation.GetDiagnostics().AddRange(generatorDiagnostics);

        return (generatedSource?.GetText().ToString(), allDiagnostics);
    }
}
