name: Get changed libraries
on:
  workflow_call:
    outputs:
      packages:
        description: "List of changed packages"
        value: string

jobs:
  detect:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Detect changed packages
        id: detect
        run: |
          # Detect changed folders under src/
          changed_packages=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
            | grep '^src/' \
            | cut -d/ -f2 \
            | sort -u)

          echo "Changed packages: $changed_packages"

          # Convert to JSON array for matrix
          json=$(echo "$changed_packages" | jq -R -s -c 'split("\n")[:-1]')
          echo "::set-output name=packages::$json"
